<a href="https://colab.research.google.com/github/Gk031098/Love-Letter/blob/main/NumPy_Lab_Topic_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RCIT4523 – Topic 3: Python & NumPy
## Hands-on Lab (2 Hours)

Welcome! Complete each activity step-by-step.
Run each cell and modify code where required.


## 🔹 Activity 1: Fix the Code
Fix the error below:

In [ ]:
x = [1,2,3,4]
for i in range(5):
    print(x[i])

# TODO: Fix the error

In [ ]:
x = [1,2,3,4]           # List has 4 elements, valid indices: 0,1,2,3
for i in range(5):      # i takes values: 0,1,2,3,4
    print(x[i])         # ERROR on i=4: x[4] doesn't exist

i=0: x[0] = 1    ✅
i=1: x[1] = 2    ✅
i=2: x[2] = 3    ✅
i=3: x[3] = 4    ✅
i=4: x[4] = ???  ❌ IndexError!

In [1]:
x = [1,2,3,4]
for i in range(len(x)):
  print(x[i])

1
2
3
4


In [2]:
x = [1,2,3,4]
for num in x:
  print(num)

1
2
3
4


## 🔹 Activity 2: Python Practice

In [ ]:
# Create list 1–10
nums = list(range(1,11))

# TODO: Squares of all numbers

# TODO: Squares of even numbers


In [3]:
nums = list(range(1,11))
squares_all = [num**2 for num in nums]
print("Squares of all:", squares_all)
squares_even = [num**2 for num in nums if num % 2 == 0]
print("Squares of even:", squares_even)

Squares of all: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
Squares of even: [4, 16, 36, 64, 100]


In [ ]:
# Dictionary task
students = {
    "Ali": 80,
    "Siti": 45,
    "John": 60
}

# TODO: Print students with marks > 50


In [6]:
students = {
    "Ali": 80,
    "Siti": 45,
    "John": 60
}

for name, score in students.items():
  if score > 50:
    print(f"{name}: {score}")

Ali: 80
John: 60


## 🔹 Activity 3: NumPy Basics

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.zeros((2,2))
c = np.ones((2,3))

print(a)
print(b)
print(c)

# TODO: Print shapes

In [8]:
import numpy as np

a = np.array([1,2,3])
b = np.zeros((2,2))
c = np.ones((2,3))

print(a)
print(b)
print(c)

print("a shape:", a.shape)
print("b shape:", b.shape)
print("c shape:", c.shape)

[1 2 3]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
a shape: (3,)
b shape: (2, 2)
c shape: (2, 3)


## 🔹 Activity 4: Indexing

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

# TODO:
# 1. First row
# 2. Second column
# 3. Submatrix [[2,3],[5,6]]


In [9]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Original array:")
print(x)

print("\n1. First row:", x[0])

print("2. Second column:", x[:, 1])

print("3. Submatrix [[2,3],[5,6]]:", x[0:2, 1:3])

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1. First row: [1 2 3]
2. Second column: [2 5 8]
3. Submatrix [[2,3],[5,6]]: [[2 3]
 [5 6]]


## 🔹 Activity 5: Array Operations

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# TODO:
# Add
# Element-wise multiply
# Matrix multiply


In [10]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print("x:")
print(x)
print("y:")
print(y)

print("\nAdd (x + y):")
print(x + y)

print("\nElement-wise multiply (x * y):")
print(x * y)

print("\nMatrix multiply (x @ y):")
print(x @ y)

x:
[[1 2]
 [3 4]]
y:
[[5 6]
 [7 8]]

Add (x + y):
[[ 6  8]
 [10 12]]

Element-wise multiply (x * y):
[[ 5 12]
 [21 32]]

Matrix multiply (x @ y):
[[19 22]
 [43 50]]


## 🔹 Activity 6: Boolean Indexing

In [ ]:
a = np.array([1,2,3,4,5])

# TODO: Select values > 3


In [11]:
import numpy as np

a = np.array([1,2,3,4,5])

mask = a > 3
print("Boolean mask:", mask)
print("Values > 3:", a[mask])

Boolean mask: [False False False  True  True]
Values > 3: [4 5]


## 🔹 Activity 7: Broadcasting

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
v = np.array([1,0,1])

# Predict output before running
print(x + v)

In [ ]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])  # Shape: (2, 3)  ← 2 rows, 3 columns
v = np.array([1,0,1])            # Shape: (3,)    ← 1D array (length 3)

print(x + v)  # ❌ BROADCASTING FAILURE

Why it fails - Broadcasting Rules:

x.shape: (2, 3)    v.shape: (3,)
[2 rows][3 cols]   [length 3]

NumPy tries to stretch v.shape to match:
(3,) → (1, 3) → (2, 3)  ?  ❌ Can't stretch 1→2 automatically

In [16]:
x = np.array([[1,2,3],[4,5,6]])
v = np.array([1,0,1])

print(x + v)

[[2 2 4]
 [5 5 7]]


## 🔹 Activity 8: Mini Project

In [ ]:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [50, 65, 70]
])

# TODO:
# 1. Average per student
# 2. Average per subject
# 3. Highest mark
# 4. Students with average > 75


In [15]:
import numpy as np

marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [50, 65, 70]
])

print("Marks:")
print(marks)

avg_per_student = np.mean(marks, axis=1)
print("\n1. Average per student:", avg_per_student)

avg_per_subject = np.mean(marks, axis=0)
print("2. Average per subject:", avg_per_subject)

highest = np.max(marks)
print("3. Highest mark:", highest)

top_students = np.where(avg_per_student > 75)[0]
print("4. Students with avg > 75 (indices):", top_students)
print("Their averages:", avg_per_student[top_students])

Marks:
[[70 80 90]
 [60 75 85]
 [50 65 70]]

1. Average per student: [80.         73.33333333 61.66666667]
2. Average per subject: [60.         73.33333333 81.66666667]
3. Highest mark: 90
4. Students with avg > 75 (indices): [0]
Their averages: [80.]
